dist: trusty

services:
  - docker

script:
  - docker build -t faf-unitdb .

after_success:
  - export REPO=faforever/faf-unitdb
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
      docker tag faf-unitdb ${REPO}:${TRAVIS_TAG};
      docker push ${REPO};
    fi

after_failure:
  - docker logs faf-unitdb